# Generated by Django 6.0.2 on 2026-02-21 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_provozu', models.IntegerField()),
                ('nazev', models.CharField(max_length=255)),
                ('ulice', models.CharField(max_length=255)),
                ('mesto', models.CharField(max_length=255)),
                ('kraj', models.CharField(max_length=255)),
                ('psc', models.CharField(max_length=20)),
                ('manazer', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_provozu', 'Manažer provozu'), ('oblastni_manager', 'Oblastní manažer'), ('hr', 'HR'), ('reditelka', 'Ředitelka')], max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
