# Generated by Django 6.0.2 on 2026-02-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spravovane_provozy',
            field=models.ManyToManyField(blank=True, help_text='Provozy, za které tento uživatel odpovídá (manažer provozu / oblastní manažer).', related_name='spravujici_uzivatele', to='core.provoz', verbose_name='Spravované provozy'),
        ),
    ]
