# Generated by Django 6.0.2 on 2026-02-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_spravovane_provozy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True)),
                ('kod', models.CharField(help_text='Strojový kód, např. KUCHAR, SEFKUCHAR, MANAZER_PROVOZU…', max_length=50, unique=True)),
                ('typ_pomeru', models.CharField(choices=[('HPP', 'HPP'), ('DPC', 'Dohoda o pracovní činnosti'), ('DPP', 'Dohoda o provedení práce')], default='HPP', max_length=3)),
                ('aktivni', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nazev'],
            },
        ),
    ]
