# Generated by Django 6.0.2 on 2026-02-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pozice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pozice',
            name='typ_pomeru',
        ),
    ]
