# Generated by Django 6.0.2 on 2026-02-21 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OsobniDotaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum založení')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum poslední změny')),
                ('titul', models.CharField(blank=True, help_text='Např. Bc., Mgr., Ing.', max_length=50, verbose_name='Titul')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('rodna_prijmeni', models.CharField(blank=True, max_length=255, verbose_name='Rodné a všechna dřívější příjmení')),
                ('datum_narozeni', models.DateField(verbose_name='Datum narození')),
                ('misto_narozeni', models.CharField(max_length=255, verbose_name='Místo narození')),
                ('statni_obcanstvi', models.CharField(max_length=255, verbose_name='Státní občanství')),
                ('rodinny_stav', models.CharField(blank=True, max_length=255, verbose_name='Rodinný stav')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('rodne_cislo', models.CharField(max_length=20, verbose_name='Rodné číslo')),
                ('zdravotni_pojistovna', models.CharField(max_length=255, verbose_name='Zdravotní pojišťovna')),
                ('cislo_uctu', models.CharField(max_length=50, verbose_name='Číslo účtu')),
                ('kod_banky', models.CharField(max_length=10, verbose_name='Kód banky')),
                ('nazev_banky', models.CharField(blank=True, max_length=255, verbose_name='Název banky / spořitelny')),
                ('trvale_ulice', models.CharField(max_length=255, verbose_name='Trvalé bydliště – ulice')),
                ('trvale_cislo_popisne', models.CharField(max_length=50, verbose_name='Trvalé bydliště – číslo popisné/orientační')),
                ('trvale_mesto', models.CharField(max_length=255, verbose_name='Trvalé bydliště – město/obec')),
                ('trvale_psc', models.CharField(max_length=20, verbose_name='Trvalé bydliště – PSČ')),
                ('dorucovaci_ulice', models.CharField(max_length=255, verbose_name='Doručovací adresa – ulice')),
                ('dorucovaci_cislo_popisne', models.CharField(max_length=50, verbose_name='Doručovací adresa – číslo popisné/orientační')),
                ('dorucovaci_mesto', models.CharField(max_length=255, verbose_name='Doručovací adresa – město/obec')),
                ('dorucovaci_psc', models.CharField(max_length=20, verbose_name='Doručovací adresa – PSČ')),
                ('duchod_predcasny', models.BooleanField(default=False, verbose_name='Předčasný důchod')),
                ('duchod_starobni', models.BooleanField(default=False, verbose_name='Starobní důchod')),
                ('duchod_invalidni', models.BooleanField(default=False, verbose_name='Invalidní důchod')),
                ('duchod_datum_vzniku', models.CharField(blank=True, max_length=255, verbose_name='Datum vzniku nároku na důchod')),
                ('duchod_kdo_vyplaci', models.CharField(blank=True, max_length=255, verbose_name='Kdo důchod vyplácí')),
                ('duchod_kdo_dopl_info', models.CharField(blank=True, max_length=255, verbose_name='Další informace k důchodu')),
                ('vzdelani_zakladni', models.BooleanField(default=False, verbose_name='Základní škola')),
                ('vzdelani_sou', models.BooleanField(default=False, verbose_name='Střední odborné učiliště')),
                ('vzdelani_ss', models.BooleanField(default=False, verbose_name='Střední škola')),
                ('vzdelani_gymnazium', models.BooleanField(default=False, verbose_name='Gymnázium')),
                ('vzdelani_vs', models.BooleanField(default=False, verbose_name='Vysoká škola')),
                ('vzdelani_misto_studia', models.CharField(blank=True, max_length=255, verbose_name='Vzdělání – místo studia')),
                ('vzdelani_cr_zahranici', models.CharField(blank=True, max_length=50, verbose_name='Vzdělání – ČR / zahraničí')),
                ('vzdelani_rok_ukonceni', models.CharField(blank=True, max_length=10, verbose_name='Vzdělání – rok ukončení')),
                ('vzdelani_mesto_obec', models.CharField(blank=True, max_length=255, verbose_name='Vzdělání – město/obec')),
                ('vzdelani_skola_nazev', models.CharField(blank=True, max_length=255, verbose_name='Vzdělání – škola (název)')),
                ('vzdelani_obor', models.CharField(blank=True, max_length=255, verbose_name='Vzdělání – obor')),
                ('vzdelani_zakonceno_vyucni_list', models.BooleanField(default=False, verbose_name='Zakončeno – výuční list')),
                ('vzdelani_zakonceno_maturita', models.BooleanField(default=False, verbose_name='Zakončeno – maturitní vysvědčení')),
                ('vzdelani_zakonceno_diplom', models.BooleanField(default=False, verbose_name='Zakončeno – diplom')),
                ('posledni_zam_nazev_firmy', models.CharField(blank=True, max_length=255, verbose_name='Poslední zaměstnavatel – název firmy')),
                ('posledni_zam_pracovni_zarazeni', models.CharField(blank=True, max_length=255, verbose_name='Poslední zaměstnavatel – pracovní zařazení')),
                ('posledni_zam_od', models.CharField(blank=True, max_length=50, verbose_name='Poslední zaměstnavatel – od')),
                ('posledni_zam_do', models.CharField(blank=True, max_length=50, verbose_name='Poslední zaměstnavatel – do')),
                ('cizinec_cislo_dokladu', models.CharField(blank=True, max_length=100, verbose_name='Číslo dokladu totožnosti (OP/PAS)')),
                ('cizinec_povoleni_prace', models.CharField(blank=True, max_length=255, verbose_name='Povolení k výkonu práce')),
                ('cizinec_povoleni_pobytu', models.CharField(blank=True, max_length=255, verbose_name='Povolení k pobytu na území ČR')),
                ('cizinec_adresa_ulice', models.CharField(blank=True, max_length=255, verbose_name='Adresa cizince v ČR – ulice')),
                ('cizinec_adresa_cislo', models.CharField(blank=True, max_length=50, verbose_name='Adresa cizince v ČR – číslo popisné/orientační')),
                ('cizinec_adresa_stat_mesto', models.CharField(blank=True, max_length=255, verbose_name='Adresa cizince v ČR – stát/město')),
                ('cizinec_adresa_psc', models.CharField(blank=True, max_length=20, verbose_name='Adresa cizince v ČR – PSČ')),
                ('pojisteni_cizina_byl', models.BooleanField(default=False, verbose_name='Účast na důchodovém pojištění v cizině – byl/a')),
                ('pojisteni_cizina_nazev_adresa_nositele', models.TextField(blank=True, verbose_name='Název a adresa cizozemského nositele pojištění')),
                ('pojisteni_cizina_cislo_pojisteni', models.CharField(blank=True, max_length=255, verbose_name='Číslo cizozemského pojištění')),
                ('srazky_existuji', models.BooleanField(default=False, verbose_name='Nařízené srážky ze mzdy existují')),
                ('srazky_vymahajici_orgam_a_cj', models.TextField(blank=True, verbose_name='Vymáhající orgán a číslo jednací (srážky)')),
                ('pocet_vyzivovanych_osob', models.PositiveIntegerField(default=0, verbose_name='Počet vyživovaných osob')),
                ('zmenena_prac_schopnost', models.BooleanField(default=False, verbose_name='Změněná pracovní schopnost')),
                ('vedeni_v_evidenci_up', models.BooleanField(default=False, verbose_name='Veden v evidenci úřadu práce')),
                ('jiny_pracovni_pomer', models.BooleanField(default=False, verbose_name='Mám ještě jiný pracovní poměr')),
                ('je_osvc', models.BooleanField(default=False, verbose_name='Jsem OSVČ')),
                ('zapoctovy_list_predlozen', models.BooleanField(default=False, verbose_name='Zápočtový list předložen')),
                ('cisty_trestni_rejstrik', models.BooleanField(default=False, verbose_name='Čistý trestní rejstřík')),
                ('jine_poznamky', models.TextField(blank=True, verbose_name='Jiné (poznámky)')),
                ('potvrzeni_podpis_text', models.TextField(blank=True, verbose_name='Text k podpisu zaměstnance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotazniky_vytvorene', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil (uživatel)')),
            ],
        ),
    ]
