# Generated by Django 6.0.2 on 2026-02-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='stav',
            field=models.CharField(choices=[('draft', 'Rozpracovaný (provoz)'), ('provoz_odeslal', 'Odesláno z provozu'), ('hr_kontroluje', 'HR kontroluje'), ('hr_schvaleno', 'Schváleno HR'), ('vraceno_provoz', 'Vráceno na doplnění provozu')], default='draft', max_length=32, verbose_name='Stav dotazníku'),
        ),
    ]
