# Generated by Django 6.0.2 on 2026-02-21 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pozice'),
        ('osobni_dotaznik', '0002_osobnidotaznik_stav'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='pozice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dotazniky', to='core.pozice'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='provoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dotazniky', to='core.provoz'),
        ),
    ]
