# Generated by Django 6.0.2 on 2026-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0003_osobnidotaznik_pozice_osobnidotaznik_provoz'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='typ_pomeru',
            field=models.CharField(blank=True, choices=[('HPP', 'Hlavní pracovní poměr'), ('DPP', 'Dohoda o provedení práce'), ('DPC', 'Dohoda o pracovní činnosti')], max_length=10, null=True, verbose_name='Typ pracovního poměru'),
        ),
    ]
