# Generated by Django 6.0.2 on 2026-02-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0004_osobnidotaznik_typ_pomeru'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsobniDotaznikPriloha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soubor', models.FileField(upload_to='dotaznik_prilohy/', verbose_name='Soubor')),
                ('popis', models.CharField(blank=True, max_length=255, verbose_name='Popis (např. OP, potvrzení, ...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dotaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prilohy', to='osobni_dotaznik.osobnidotaznik')),
            ],
        ),
    ]
