# Generated by Django 6.0.2 on 2026-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0005_osobnidotaznikpriloha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='dorucovaci_cislo_popisne',
            field=models.CharField(blank=True, max_length=50, verbose_name='Doručovací adresa – číslo popisné/orientační'),
        ),
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='dorucovaci_mesto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Doručovací adresa – město/obec'),
        ),
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='dorucovaci_psc',
            field=models.CharField(blank=True, max_length=20, verbose_name='Doručovací adresa – PSČ'),
        ),
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='dorucovaci_ulice',
            field=models.CharField(blank=True, max_length=255, verbose_name='Doručovací adresa – ulice'),
        ),
        migrations.AlterField(
            model_name='osobnidotaznikpriloha',
            name='soubor',
            field=models.FileField(blank=True, null=True, upload_to='dotaznik_prilohy/', verbose_name='Soubor'),
        ),
    ]
