# Generated by Django 6.0.2 on 2026-02-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0006_alter_osobnidotaznik_dorucovaci_cislo_popisne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='mzda_hruba',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Např. 25000.00 nebo hodinová sazba', max_digits=10, null=True, verbose_name='Hrubá mzda / odměna'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='pracovni_doba_popis',
            field=models.CharField(blank=True, help_text='Např. dvousměnný provoz, PO–PÁ, krátký/dlouhý týden…', max_length=255, verbose_name='Rozvržení pracovní doby'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='uvazek_fte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Např. 1.00, 0.75, 0.50', max_digits=4, null=True, verbose_name='Úvazek (FTE)'),
        ),
    ]
