# Generated by Django 6.0.2 on 2026-02-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0007_osobnidotaznik_mzda_hruba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='stav',
            field=models.CharField(choices=[('draft', 'Rozpracovaný (provoz)'), ('provoz_odeslal', 'Odesláno z provozu'), ('hr_kontroluje', 'HR kontroluje'), ('hr_schvalil', 'Schváleno HR'), ('vraceno_provozu', 'Vráceno na doplnění provozu')], default='draft', max_length=32, verbose_name='Stav dotazníku'),
        ),
    ]
