# Generated by Django 6.0.2 on 2026-02-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0008_alter_osobnidotaznik_stav'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='hr_poznamka_pro_provoz',
            field=models.TextField(blank=True, verbose_name='Poznámka HR pro provoz'),
        ),
    ]
