# Generated by Django 6.0.2 on 2026-02-22 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0009_osobnidotaznik_hr_poznamka_pro_provoz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='hr_posledni_kontrola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotazniky_kontrolovane_hr', to=settings.AUTH_USER_MODEL, verbose_name='Poslední kontrola HR'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='hr_posledni_kontrola_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum poslední HR kontroly'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='hr_schvalil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotazniky_schvalene_hr', to=settings.AUTH_USER_MODEL, verbose_name='Schválil HR'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='hr_schvalil_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum schválení HR'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='hr_vraceno_provozu_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum vrácení na provoz'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='hr_vratil_provozu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotazniky_vracene_provozu_hr', to=settings.AUTH_USER_MODEL, verbose_name='Vrátil na provoz'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='odeslal_na_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotazniky_odeslane_na_hr', to=settings.AUTH_USER_MODEL, verbose_name='Odeslal na HR'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='odeslal_na_hr_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Odesláno na HR'),
        ),
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotazniky_vytvorene', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil uživatel'),
        ),
    ]
