# Generated by Django 6.0.2 on 2026-02-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0010_osobnidotaznik_hr_posledni_kontrola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='datum_nastupu',
            field=models.DateField(blank=True, null=True, verbose_name='Datum nástupu do práce'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='doba_trvani',
            field=models.CharField(blank=True, choices=[('neurcita', 'Na dobu neurčitou'), ('urcita', 'Na dobu určitou')], max_length=20, null=True, verbose_name='Doba trvání pracovního poměru'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='doba_urcita_do',
            field=models.DateField(blank=True, help_text='Vyplňte pouze pokud jde o dobu určitou.', null=True, verbose_name='Doba určitá do'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='zkusebni_doba_mesice',
            field=models.PositiveIntegerField(blank=True, help_text='Např. 3 měsíce', null=True, verbose_name='Délka zkušební doby (měsíce)'),
        ),
    ]
