# Generated by Django 6.0.2 on 2026-02-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0011_osobnidotaznik_datum_nastupu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerovanyDokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('mzdovy_vymer', 'Mzdový výměr'), ('pracovni_smlouva', 'Pracovní smlouva')], max_length=100)),
                ('docx_soubor', models.FileField(blank=True, upload_to='dokumenty/docx/')),
                ('pdf_soubor', models.FileField(blank=True, upload_to='dokumenty/pdf/')),
                ('vygenerovano', models.DateTimeField(auto_now_add=True)),
                ('dotaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumenty', to='osobni_dotaznik.osobnidotaznik')),
            ],
        ),
    ]
