# Generated by Django 6.0.2 on 2026-02-22 12:15

import osobni_dotaznik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0012_generovanydokument'),
    ]

    operations = [
        migrations.AddField(
            model_name='generovanydokument',
            name='nazev',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='generovanydokument',
            name='docx_soubor',
            field=models.FileField(blank=True, upload_to=osobni_dotaznik.models.dokument_upload_to),
        ),
        migrations.AlterField(
            model_name='generovanydokument',
            name='pdf_soubor',
            field=models.FileField(blank=True, upload_to=osobni_dotaznik.models.dokument_upload_to),
        ),
        migrations.AlterField(
            model_name='generovanydokument',
            name='typ',
            field=models.CharField(choices=[('mzdovy_vymer', 'Mzdový výměr')], max_length=100),
        ),
    ]
