# Generated by Django 6.0.2 on 2026-02-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0013_generovanydokument_nazev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='datumnastupu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='doba_urcita_do',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='zkusebni_doba_mesice',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
