# Generated by Django 6.0.2 on 2026-02-22 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0014_osobnidotaznik_datumnastupu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osobnidotaznik',
            name='datumnastupu',
        ),
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotazniky_vytvorene', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil (uživatel)'),
        ),
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='doba_urcita_do',
            field=models.DateField(blank=True, help_text='Vyplňte pouze pokud jde o dobu určitou.', null=True, verbose_name='Doba určitá do'),
        ),
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='zkusebni_doba_mesice',
            field=models.PositiveIntegerField(blank=True, help_text='Např. 3 měsíce', null=True, verbose_name='Délka zkušební doby (měsíce)'),
        ),
    ]
