# Generated by Django 6.0.2 on 2026-02-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobni_dotaznik', '0015_remove_osobnidotaznik_datumnastupu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='zkusebka_konec',
            field=models.DateField(blank=True, null=True, verbose_name='Konec zkušební doby'),
        ),
    ]
